/*
 * Region list
 */
package com.faisalman.phoneidentifier;

import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author Faisal Salman
 */
public class Region {
    public String code;
    public String name;
    public Region(String code) {
        this.code = code;
        this.name = this.map.containsKey(code) ? this.map.get(code) : "";
    }
    private static final Map<String, String> map;
    static {
        Map<String, String> map = new HashMap<String, String>();
        map.put("21", "Jakarta");
        map.put("22", "Bandung");
        map.put("231", "Cirebon");
        map.put("232", "Kuningan");
        map.put("233", "Majalengka");
        map.put("234", "Indramayu");
        map.put("24", "Semarang");
        map.put("261", "Sumedang");
        map.put("262", "Garut");
        map.put("263", "Cianjur");
        map.put("264", "Purwakarta");
        map.put("265", "Tasikmalaya");
        map.put("266", "Sukabumi");
        map.put("267", "Karawang");
        map.put("271", "Solo");
        map.put("272", "Klaten");
        map.put("273", "Wonogiri");
        map.put("274", "Yogyakarta");
        map.put("275", "Purworejo");
        map.put("276", "Boyolali");
        map.put("280", "Cilacap");
        map.put("281", "Banyumas");
        map.put("282", "Cilacap");
        map.put("283", "Tegal");
        map.put("284", "Pemalang");
        map.put("285", "Pekalongan");
        map.put("286", "Wonosobo");
        map.put("287", "Kebumen");
        map.put("289", "Bumiayu");
        map.put("291", "Kudus");
        map.put("292", "Grobogan");
        map.put("293", "Magelang");
        map.put("294", "Kendal");
        map.put("295", "Pati");
        map.put("296", "Blora");
        map.put("297", "Karimun Jawa");
        map.put("298", "Salatiga");
        map.put("31", "Surabaya");
        map.put("321", "");
        map.put("322", "");
        map.put("323", "");
        map.put("324", "");
        map.put("325", "");
        map.put("326", "");
        map.put("327", "");
        map.put("328", "");
        map.put("331", "");
        map.put("332", "");
        map.put("333", "");
        map.put("334", "");
        map.put("335", "");
        map.put("338", "");
        map.put("341", "");
        map.put("342", "");
        map.put("343", "");
        map.put("351", "");
        map.put("352", "");
        map.put("353", "");
        map.put("354", "");
        map.put("355", "");
        map.put("356", "");
        map.put("357", "");
        map.put("358", "");
        map.put("361", "");
        map.put("362", "");
        map.put("363", "");
        map.put("365", "");
        map.put("366", "");
        map.put("368", "");
        map.put("370", "");
        map.put("371", "");
        map.put("372", "");
        map.put("373", "");
        map.put("374", "");
        map.put("376", "");
        map.put("379", "");
        map.put("380", "");
        map.put("381", "");
        map.put("382", "");
        map.put("383", "");
        map.put("384", "");
        map.put("385", "");
        map.put("386", "");
        map.put("387", "");
        map.put("388", "");
        map.put("389", "");
        map.put("401", "");
        map.put("402", "");
        map.put("403", "");
        map.put("404", "");
        map.put("405", "");
        map.put("408", "");
        map.put("409", "");
        map.put("410", "");
        map.put("411", "");
        map.put("413", "");
        map.put("414", "");
        map.put("417", "");
        map.put("418", "");
        map.put("419", "");
        map.put("420", "");
        map.put("421", "");
        map.put("422", "");
        map.put("423", "");
        map.put("426", "");
        map.put("427", "");
        map.put("428", "");
        map.put("430", "");
        map.put("431", "");
        map.put("432", "");
        map.put("434", "");
        map.put("435", "");
        map.put("438", "");
        map.put("443", "");
        map.put("450", "");
        map.put("451", "");
        map.put("452", "");
        map.put("453", "");
        map.put("457", "");
        map.put("458", "");
        map.put("461", "");
        map.put("462", "");
        map.put("464", "");
        map.put("471", "");
        map.put("473", "");
        map.put("474", "");
        map.put("481", "");
        map.put("482", "");
        map.put("484", "");
        map.put("485", "");
        map.put("485", "");
        map.put("511", "");
        map.put("512", "");
        map.put("513", "");
        map.put("517", "");
        map.put("518", "");
        map.put("519", "");
        map.put("526", "");
        map.put("527", "");
        map.put("531", "");
        map.put("532", "");
        map.put("534", "");
        map.put("535", "");
        map.put("537", "");
        map.put("541", "");
        map.put("542", "");
        map.put("543", "");
        map.put("545", "");
        map.put("548", "");
        map.put("549", "");
        map.put("551", "");
        map.put("552", "");
        map.put("553", "");
        map.put("554", "");
        map.put("556", "");
        map.put("561", "");
        map.put("562", "");
        map.put("563", "");
        map.put("564", "");
        map.put("565", "");
        map.put("567", "");
        map.put("568", "");
        map.put("61", "Medan");
        this.map = map;
    }
}